"use client";

import { X, Shield, Lock } from "lucide-react";
import { useEffect } from "react";

type LegalModalProps = {
    isOpen: boolean;
    onClose: () => void;
    type: "privacy" | "terms";
};

export function LegalModal({ isOpen, onClose, type }: LegalModalProps) {
    // Prevent scrolling when modal is open
    useEffect(() => {
        if (isOpen) {
            document.body.style.overflow = "hidden";
        } else {
            document.body.style.overflow = "unset";
        }
        return () => { document.body.style.overflow = "unset"; };
    }, [isOpen]);

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm transition-opacity"
                onClick={onClose}
            />

            {/* Modal Content */}
            <div className="relative w-full max-w-2xl bg-white dark:bg-slate-900 rounded-[2rem] shadow-2xl flex flex-col max-h-[90vh] animate-in fade-in zoom-in-95 duration-200 border border-slate-200 dark:border-white/10">
                {/* Header */}
                <div className="flex items-center justify-between p-8 border-b border-slate-100 dark:border-white/5 bg-slate-50/50 dark:bg-white/[0.02] rounded-t-[2rem]">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-indigo-500/10 flex items-center justify-center">
                            {type === "privacy" ? <Lock className="w-5 h-5 text-indigo-500" /> : <Shield className="w-5 h-5 text-indigo-500" />}
                        </div>
                        <h2 className="text-2xl font-bold text-foreground">
                            {type === "privacy" ? "Data Privacy Promise" : "Terms of Service"}
                        </h2>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-slate-100 dark:hover:bg-white/10 rounded-full transition-colors"
                    >
                        <X className="w-6 h-6 text-muted-foreground" />
                    </button>
                </div>

                {/* Scrollable Body */}
                <div className="p-8 overflow-y-auto custom-scrollbar space-y-6 text-muted-foreground leading-relaxed">
                    {type === "privacy" ? (
                        <>
                            <p>At <strong>Brush4Laughs</strong>, we treat your memories with the same respect we treat our own family traditions.</p>

                            <h3 className="text-foreground font-bold text-lg mt-6">1. Your Photos are Yours</h3>
                            <p>We do not claim ownership of any images you upload. Your photos are used solely for the purpose of generating your paint-by-number guide.</p>

                            <h3 className="text-foreground font-bold text-lg mt-6">2. Automatic Deletion</h3>
                            <p>We believe in "Data Minimalism". All uploaded images and generated PDFs are automatically deleted from our servers within <strong>24 hours</strong>. We do not build long-term databases of user photos.</p>

                            <h3 className="text-foreground font-bold text-lg mt-6">3. No Third-Party Sharing</h3>
                            <p>We do not sell, trade, or share your personal photos with third parties, advertisers, or AI training datasets.</p>
                        </>
                    ) : (
                        <>
                            <p>Welcome to the Brush4Laughs Studio.</p>

                            <h3 className="text-foreground font-bold text-lg mt-6">1. Personal Use Only</h3>
                            <p>The templates generated by this tool are intended for personal, non-commercial use. Create gifts, decorate your home, and have fun!</p>

                            <h3 className="text-foreground font-bold text-lg mt-6">2. User Conduct</h3>
                            <p>Please do not upload illegal, offensive, or harmful imagery. We reserve the right to refuse service for content that violates our community standards.</p>

                            <h3 className="text-foreground font-bold text-lg mt-6">3. Liability</h3>
                            <p>This tool uses automated processing. While we strive for perfection, we cannot guarantee that every detail of a complex photo will be preserved exactly as seen on screen. Always check your preview!</p>
                        </>
                    )}
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-slate-100 dark:border-white/5 bg-slate-50/50 dark:bg-white/[0.02] rounded-b-[2rem] flex justify-end">
                    <button
                        onClick={onClose}
                        className="px-6 py-2 bg-indigo-600 text-white font-bold rounded-xl hover:bg-indigo-700 transition-colors"
                    >
                        Understood
                    </button>
                </div>
            </div>
        </div>
    );
}
