export const paintcolors = [
    { name: "White", hex: "#FFFFFF" },
    { name: "Black", hex: "#000000" },
    { name: "Titanium White", hex: "#F6F9FA" },
    { name: "Lamp Black", hex: "#2C2C2C" },
    { name: "Burnt Umber", hex: "#8A3324" },
    { name: "Burnt Sienna", hex: "#E97451" },
    { name: "Raw Sienna", hex: "#C76114" },
    { name: "Yellow Ochre", hex: "#CC7722" },
    { name: "Cadmium Red", hex: "#E30022" },
    { name: "Crimson Alizarin", hex: "#E32636" },
    { name: "Cadmium Orange", hex: "#ED872D" },
    { name: "Cadmium Yellow", hex: "#FFF600" },
    { name: "Lemon Yellow", hex: "#FFF44F" },
    { name: "Sap Green", hex: "#507D2A" },
    { name: "Hooker's Green", hex: "#49796B" },
    { name: "Viridian", hex: "#40826D" },
    { name: "Phthalo Green", hex: "#123524" },
    { name: "Ultramarine Blue", hex: "#4166F5" },
    { name: "Cobalt Blue", hex: "#0047AB" },
    { name: "Phthalo Blue", hex: "#000F89" },
    { name: "Cerulean Blue", hex: "#2A52BE" },
    { name: "Violet", hex: "#8F00FF" },
    { name: "Purple", hex: "#800080" },
    { name: "Magenta", hex: "#FF00FF" },
    { name: "Rose", hex: "#FF007F" },
    { name: "Beige", hex: "#F5F5DC" },
    { name: "Cream", hex: "#FFFDD0" },
    { name: "Grey", hex: "#808080" },
    { name: "Payne's Grey", hex: "#536878" },
    { name: "Sky Blue", hex: "#87CEEB" },
    { name: "Navy", hex: "#000080" },
    { name: "Teal", hex: "#008080" },
    { name: "Turquoise", hex: "#40E0D0" },
    { name: "Lime Green", hex: "#32CD32" },
    { name: "Forest Green", hex: "#228B22" },
    { name: "Olive", hex: "#808000" },
    { name: "Brown", hex: "#A52A2A" },
    { name: "Tan", hex: "#D2B48C" },
    { name: "Sand", hex: "#C2B280" },
    { name: "Peach", hex: "#FFE5B4" },
    { name: "Coral", hex: "#FF7F50" },
    { name: "Salmon", hex: "#FA8072" },
    { name: "Pink", hex: "#FFC0CB" },
    { name: "Lavender", hex: "#E6E6FA" },
    { name: "Lilac", hex: "#C8A2C8" },
    { name: "Gold", hex: "#FFD700" },
    { name: "Silver", hex: "#C0C0C0" },
    { name: "Bronze", hex: "#CD7F32" }
];
